receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

# Uncomment the lines below if you want
# to transform the logs to JSON as part
# of the processor.
# processors:
#   transform:
#     error_mode: propagate
#     log_statements:
#       - set(log.body, ParseJSON(log.body))

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    logs:
      receivers: [otlp]
      # Uncomment the lines below if you want
      # to transform the logs to JSON as part
      # of the processor.
      # processors: [transform]
      exporters: [debug, otlphttp]
