{
 "title": "Calico Flow Logs OTLP/HTTP Exporter",
 "description": "Information about flow logs in Calico",
 "tags": [
  "calico",
  "goldmane",
  "otlp",
  "logs",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Flow by Destination Type",
   "type": "piechart",
   "description": "Show distribution of flows by Destination Type (WorkloadEndpoint/NetworkSet/etc)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (destType) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json destType=\"Key.destType\" | destType != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ destType }}"
    }
   ]
  },
  {
   "title": "Flow by protocol (L4)",
   "type": "piechart",
   "description": "Show distribution of flows by L4 protocol",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (proto) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json proto=\"Key.proto\" | proto != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ proto }}"
    }
   ]
  },
  {
   "title": "Flow by Action",
   "type": "piechart",
   "description": "Show distribution of flows by Action (Allow/Deny)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(action) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json action=\"Key.action\" | action != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "Traffic quantity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Ingress by receiver",
   "type": "piechart",
   "description": "Ingress traffic by receiver",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (Key_destName) (\n    sum_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | unwrap bytes(bytesIn)[$__auto])\n    )\n)",
     "legendFormat": "{{ Key_destName }}"
    }
   ]
  },
  {
   "title": "Egress by sender",
   "type": "piechart",
   "description": "Egress traffic by sender",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (Key_sourceName) (\n    sum_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | unwrap bytes(bytesOut)[$__auto])\n    )\n)",
     "legendFormat": "{{ Key_sourceName }}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Packets in by receiver",
   "type": "piechart",
   "description": "Packets in by receiver",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (Key_destName) (\n    sum_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | unwrap packetsIn[$__auto])\n    )\n)",
     "legendFormat": "{{ Key_destName }}"
    }
   ]
  },
  {
   "title": "Packets out by sender",
   "type": "piechart",
   "description": "Packets out by sender",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (Key_sourceName) (\n    sum_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | unwrap packetsOut[$__auto])\n    )\n)",
     "legendFormat": "{{ Key_sourceName }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Denied traffic",
   "type": "logs",
   "description": "Show all traffic where action is \"Deny\"",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | Key_action = \"Deny\" | line_format \"Src: {{.Key_sourceName}} - Dst: {{.Key_destName}}. Dst Port: {{.Key_destPort}}\""
    }
   ]
  }
 ]
}