{
 "title": "Calico Flow Logs OTLP/HTTP Exporter",
 "description": "Information about flow logs in Calico",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Flow by Destination Type",
   "type": "piechart",
   "description": "Show distribution of flows by Destination Type (WorkloadEndpoint/NetworkSet/etc)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (destType) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json destType=\"Key.destType\" | destType != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ destType }}"
    }
   ]
  },
  {
   "title": "Flow by protocol (L4)",
   "type": "piechart",
   "description": "Show distribution of flows by L4 protocol",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (proto) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json proto=\"Key.proto\" | proto != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ proto }}"
    }
   ]
  },
  {
   "title": "Flow by Action",
   "type": "piechart",
   "description": "Show distribution of flows by Action (Allow/Deny)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(action) (\n    count_over_time(\n        ({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json action=\"Key.action\" | action != \"\")[$__auto]\n    )\n)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Packets in by source",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (source) (\n    rate({service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | __error__=\"\" | label_format source=\"{{ .Key_sourceName }}\" | unwrap packetsIn [$__auto])\n)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Denied traffic",
   "type": "logs",
   "description": "Show all traffic where action is \"Deny\"",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"calico-flow-logs-otlphttp-exporter\"} | json | Key_action = \"Deny\" | line_format \"Src: {{.Key_sourceName}} - Dst: {{.Key_destName}}. Dst Port: {{.Key_destPort}}\""
    }
   ]
  }
 ]
}