name: "Generate next semver for PR"

on:
  pull_request:
    branches: ["main"]

jobs:
  generate-next-semver:
    name: Generate next semver
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get next version (main branch)
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
